include $(GOROOT)/src/Make.inc 

TARG=github.com/cihub/sealog/common

GOFILES=\
	loglevel.go \
	context.go \
	constraints.go \
	exception.go \
	flusher.go \
	closer.go \

include $(GOROOT)/src/Make.pkg
